main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.about, name="about"),
    path("home/", views.home, name="home"),
    path("redcups/", views.redcups_index, name="index"),
    path("redcups/<int:redcup_id>/", views.redcups_detail, name="detail"),
    path("redcups/create/", views.RedcupCreate.as_view(), name="redcups_create"),
    path("accounts/signup/", views.signup, name="signup"),
    path(
        "redcups/<int:pk>/update/", views.RedcupUpdate.as_view(), name="redcup_update"
    ),
    path(
        "redcups/<int:pk>/delete/", views.RedcupDelete.as_view(), name="redcup_delete"
    ),
    path("redcups/<int:redcup_id>/add_comment/", views.add_comment, name="add_comment"),
    path(
        "redcups/<int:pk>/commentupdate/",
        views.CommentUpdate.as_view(),
        name="comment_update",
    ),
    path(
        "redcups/<int:pk>/commentdelete/",
        views.CommentDelete.as_view(),
        name="comment_delete",
    ),
    path(
        "redcups/<int:pk>/photodelete/",
        views.PhotoDelete.as_view(),
        name="photo_delete",
    ),
    path("redcups/<int:redcup_id>/add_photo/", views.add_photo, name="add_photo"),
    path("chat/<str:room_name>/", views.room, name="room"),
    path("game/", views.game, name="game"),
]

redcup/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_app.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime


class Redcup(models.Model):
    name = models.CharField(max_length=100)
    rules = models.TextField(max_length=2000, default="Put your rules here!")
    players = models.IntegerField(default=1)
    link = models.URLField(
        max_length=200, default="https://www.youtube.com/watch?v=MpnTP5V5IfE"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"redcup_id": self.id})


class Comment(models.Model):
    created_date = models.DateTimeField(default=datetime.now, blank=True)
    comment = models.CharField(max_length=1000, default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    redcup = models.ForeignKey(Redcup, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

    class Meta:
        ordering = ["-created_date"]


class Photo(models.Model):
    url = models.CharField(max_length=200)
    redcup = models.ForeignKey(Redcup, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for redcup_id: {self.redcup_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
  class Meta:
    model = Comment
    fields = ['comment']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
from .models import Redcup, Comment, Photo
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from .forms import CommentForm


S3_BASE_URL = "https://s3-us-west-1.amazonaws.com/"
BUCKET = "redcupgames"




def signup(request):
    error_message = ""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
        else:
            error_message = "Invalid sign up - try again"
    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)


def home(request):
    return render(request, "home.html")


def about(request):
    return render(request, "about.html")



def redcups_index(request):
    redcups = Redcup.objects.filter(user=request.user)
    redcups = Redcup.objects.all()
    return render(request, "redcup/index.html", {"redcups": redcups})


class RedcupCreate(CreateView):
    model = Redcup
    fields = ["name", "rules", "players", "link"]
    success_url = "/redcups/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


def redcups_detail(request, redcup_id):
    redcup = Redcup.objects.get(id=redcup_id)
    comment_form = CommentForm()
    return render(
        request, "redcup/detail.html", {"redcup": redcup, "comment_form": comment_form}
    )


def add_photo(request, redcup_id):
    photo_file = request.FILES.get("photo-file", None)
    if photo_file:
        s3 = boto3.client("s3")
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind(".") :]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, redcup_id=redcup_id)
            photo.save()
        except:
            print("An error occurred uploading file to S3")
    return redirect("detail", redcup_id=redcup_id)


def add_comment(request, redcup_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.redcup_id = redcup_id
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        new_comment.save()
    return redirect("detail", redcup_id=redcup_id)


def index(request):
    return render(request, "chat/index.html", {})


def room(request, room_name):
    return render(request, "chat/room.html", {"room_name": room_name})


def game(request):
    return render(request, "game/game.html", {})



class RedcupUpdate(UpdateView):
    model = Redcup
    fields = "__all__"



class RedcupDelete(DeleteView):
    model = Redcup
    success_url = "/redcups/"


class CommentUpdate(UpdateView):
    model = Comment
    fields = ["comment"]
    success_url = "/redcups/{redcup_id}"



class CommentDelete(DeleteView):
    model = Comment
    success_url = "/redcups/{redcup_id}"


class PhotoDelete(DeleteView):
    model = Photo
    success_url = "/redcups/{redcup_id}"

main_app/templates/Chat/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) { 
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

main_app/templates/Chat/room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <h1>Red Cup Games Chat</h1>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100" value="{{user.username}} -"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    var roomName = "{{ room_name|escapejs }}";

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) { 
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '{{user.username}} - ';
    };
</script>
</html>

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
{% if user.is_authenticated %}


<div class="is-overlay has-text-centered single-spaced" style="top: 60px;">
  <h1 class="title is-1 has-text-danger">RED CUP GAMES</h1>
  <h1 class="title is-3 has-text-danger">PLAY HARD! DRINK HARD!</h1>
</div>

{% else %}

<div class="sign is-overlay has-text-centered single-spaced" style="top: 60px;">
  <h1 class="title is-1 has-text-black">Welcome To Red Cup Games</h1>
  <h2 class="title is-3 has-text-black">A place where you can find and share drinking games.</h2>

<p class="title is-3 has-text-black">Are you over 21?</p>
<form action="{% url 'signup' %}" method="get">
  {% csrf_token %}
  <input type="submit" class="btn" value="Yes" />
</form>
<br />

<a
  class="link"
  href="https://www.fisher-price.com/en-us/shop/age/baby-on-the-way"
  >I'm under 21</a
>
</div>
</div>

{% endif %}
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Red Cup Games</title>
		<link rel="stylesheet" 
        href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.0/css/bulma.min.css">
		<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
	</head>
<body>
  <section class="hero is-fullheight">
    <div class="hero-head">
      <div class="columns is-mobile is-marginless heading has-text-weight-bold is-size-6">
        <div class="column left">
          <p class="navbar-item has-text-danger">RED CUP GAMES</p>
        </div>
        {% if user.is_authenticated %}
        <div class="column center desktop">
          <a class="navbar-item has-text-danger desktop" href="{% url 'home' %}">HOME</a>
          <a class="navbar-item has-text-danger desktop" href="{% url 'redcups_create' %}">CREATE DRINKING GAME</a>
          <a class="navbar-item has-text-danger desktop" href="{% url 'index' %}">ALL DRINKING GAMES</a>
            </div>
        <div class="column right  ">
          <a class="navbar-item has-text-danger desktop" href="https://redcupchat.herokuapp.com/" 
              target="popup" 
              onclick="window.open('https://redcupchat.herokuapp.com/','popup','width=600,height=600'); return false;">
              Chat
          </a>
          <a class="navbar-item has-text-danger desktop" href="{% url 'logout' %}">{{user.username}}(LOG OUT)</a>
          {% else %}
          <a class="navbar-item has-text-danger desktop" href="{% url 'signup' %}">SIGN UP</a>
          <a class="navbar-item has-text-danger desktop" href="{% url 'login' %}">SIGN IN</a>
          {% endif %}
        </div>
      </div>
    <main class="container">
      {% block content %} {% endblock %}
    </main>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="is-overlay has-text-centered single-spaced" style="top: 60px;">
    <h1 class="title is-1 has-text-danger">RED CUP GAMES</h1>
    <h1 class="title is-3 has-text-danger">PLAY HARD! DRINK HARD!</h1>
</div>

{% endblock %}

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="sign">
<h1 class="title text-is-centered is-3 has-text-black">Delete Comment</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="confirmDelete">
    <input type="submit" value="Yes - Delete!" class="btn"><br>
    <a href="{% url 'detail' comment.id %}">Cancel</a>
    </div>
  </form>

</div>


{% endblock %}

main_app/templates/main_app/photo_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Game</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' redcup.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/redcup_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="sign">
<h1 class="title has-text-centered is-3 has-text-black">Delete Game</h1>

  <h4 class="title has-text-centered is-5 has-text-black">Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>
  <form action="" method="POST">
    {% csrf_token %}
  <div class="confirmDelete">
    <input type="submit" value="Yes - Delete!" class="btn"><br>
    <a href="{% url 'detail' redcup.id %}">Cancel</a>
  </div>
  </form>
</div>
</div>
{% endblock %}

main_app/templates/main_app/redcup_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
<div class="is-overlay has-text-centered single-spaced" style="top: 50px;">
  <h1 class="title is-3 has-text-black">ADD DRINKING GAME</h1>
  {% endif %}
  <div class="sign">
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </div>
  </form>
</div>
{% endblock %}

main_app/templates/redcup/detail.html
{% extends 'base.html' %} {% block content %}

<h1 class="has-text-centered title is-1 has-text-black">GAME DETAILS</h1>
<div class="has-text-left single-spaced" style="top: 50px;">
<div class="row">
  <div class="sign">
  
        <span class="card-title">{{ redcup.name }}
        <p><u> Rules:</u> {{ redcup.rules }}</p>
        <p><u>Players:</u> {{ redcup.players }}</p>
        <p>
          <u>Link:</u>
          <a href="{{ redcup.link }}" target="_blank">Click Here</a>
        </p>
        <p><u>User:</u> {{ redcup.user.username }}</p></span>
      {% if user.username == redcup.user.username %}
      <div class="card-action">
        <br>
        <a class="editD" href="{% url 'redcup_update' redcup.id %}">Edit</a>

        <a class="editD" href="{% url 'redcup_delete' redcup.id %}">Delete</a>
      </div>
      {% endif %}
</div>
</div>
</div>
<div class="row">
<div class="sign">
{% for photo in redcup.photo_set.all %}

<div class="has-text-centered single-spaced" style="top: 50px;">
      <img class="responsive-img card-panel" src="{{photo.url}}">
  {% if user.username == photo.redcup.user.username %}
  <div class="sign">
      <form action="{% url 'photo_delete' photo.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn" value="delete">
      </form>

  {% endif %}
</div>      
    {% empty %}
      <div class="card-panel teal-text center-align"></div>
    {% endfor %}
    <form action="{% url 'add_photo' redcup.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" style="width: 300px" class="btn" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>
</div>
</div>

<div class="comment">   
  <div class="is-pulled-left">
  <div class="has-text-centered single-spaced" style="top: 50px;"></div>
  <form action="{% url 'add_comment' redcup.id %}" method="post">
    {% csrf_token %} {{ comment_form.as_p }}
    <br><input type="submit" class="btn commentBtn" value="Add A Comment" /><br><br>
  </form>
  <table class="striped">
    <thead>
      <tr>
        <th><u>Date</u></th>
        <th><u>User</u></th>
        <th><u>Comment</u></th>
      </tr>
    </thead>
    <tbody>
      {% for comment in redcup.comment_set.all %}
      <tr>
        <td>{{comment.created_date}}</td>
        <td>{{comment.user.username}}</td>
        {% if user.username == comment.user.username %}
        <td>
          <form action="{% url 'comment_update' comment.id%}" method="post">
            {{comment.comment}} {% csrf_token %} {{ comment_form.as_p }}
            <div class="updateComment"><input type="submit" class="btn" value="Update Comment" /></div>
          </form>
        </td>
        <td><a class="editD" href="{% url 'comment_delete' comment.id %}">Delete</a></td>
        {% else %}
        <td>{{comment.comment}}</td>
        {% endif %} {% endfor %}
      </tr>
    </tbody>
  </table>

  <div class="card-action"></div>
</div>
</div>
{% endblock %}

main_app/templates/redcup/index.html
{% extends 'base.html' %} {% block content %}

<h1 class="has-text-centered title is-1 has-text-black">DRINKING GAMES</h1>

{% for redcup in redcups %}
<div class="has-text-centered single-spaced" style="top: 50px;">
  <div class="sign">
  <a href="{% url 'detail' redcup.id %}">
    <div class="card-content">
      <span class="card-title">{{ redcup.name }}</span>
      <p>Rules: {{ redcup.rules }}</p>
      <p>Players: {{ redcup.players }}</p>
      <p>User: {{ redcup.user.username }}</p>
    </div>
  </a>
</div>
<br>
</div>
{% endfor %} {% endblock %}